version: '3.2'

networks:
  traefik-network-shared:
    external: true

services:
  app:
    image: ${APP_IMAGE}:${IMAGE_TAG_TO_REVIEW:-master}
    labels:
      traefik.frontend.rule: Host:${DOMAIN_NAME:-app.example.com}
      traefik.docker.network: traefik-network-shared
      traefik.protocol: http
      traefik.port: 80
    deploy:
      placement:
        constraints:
        - node.labels.web-entry == true # Host with installed Traefik only
      replicas: 1
      restart_policy:
        delay: 5s
        max_attempts: 2
      resources:
        limits:
          memory: 32M
    networks:
    - traefik-network-shared
